name: main

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Test
        run: yarn && yarn test:cover

      # user codecov-action
      - name: Report
        uses: codecov/codecov-action@v1
        env:
          CI: true
